/* Regenerates oui.js from Wireshark's manuf file (IEEE MA-L / MA-M / MA-S registries, updated weekly):
     curl -L -o manuf.txt https://www.wireshark.org/download/automated/data/manuf
     node tools/mac-lookup/build-oui.js manuf.txt
   Output format: v = vendor names (most used first), l/m/s = 24/28/36-bit prefixes as
   "<hex prefix><vendor index in base 36>", comma separated. */
const fs = require('fs');
const path = require('path');
const src = process.argv[2] || 'manuf.txt';
const rows = fs.readFileSync(src, 'utf8').split('\n').filter(l => l.trim() && !l.startsWith('#'));
const names = [], idx = new Map(), entries = [];
for (const l of rows) {
  const [blk, short, long] = l.split('\t').map(s => s.trim());
  const [addr, bits] = blk.split('/');
  const hex = addr.replace(/[:\-.]/g, '').toUpperCase();
  const name = (long || short || '').replace(/\s+/g, ' ').trim();
  if (!name || /^Officially/.test(name)) continue;   // 00:00:00 placeholder
  if (!idx.has(name)) { idx.set(name, names.length); names.push(name); }
  entries.push([hex.slice(0, Math.ceil((bits ? +bits : 24) / 4)), idx.get(name)]);
}
// most used vendors get the shortest indexes
const freq = new Array(names.length).fill(0); entries.forEach(e => freq[e[1]]++);
const order = names.map((_, i) => i).sort((a, b) => freq[b] - freq[a]);
const remap = new Map(order.map((o, n) => [o, n]));
entries.sort((a, b) => (a[0] < b[0] ? -1 : 1));
const by = { 6: [], 7: [], 9: [] };
entries.forEach(([p, v]) => by[p.length].push(p + remap.get(v).toString(36)));
const date = new Date().toISOString().slice(0, 10);
const data = { date, v: order.map(o => names[o]), l: by[6].join(','), m: by[7].join(','), s: by[9].join(',') };
const out = `/* MAC address vendor prefixes: IEEE MA-L / MA-M / MA-S registries via Wireshark's manuf file, ${date}.
   Generated by build-oui.js, don't edit by hand. */
window.OUI_DATA = ${JSON.stringify(data)};
`;
fs.writeFileSync(path.join(__dirname, 'oui.js'), out);
console.log(`oui.js: ${data.v.length} vendors, ${by[6].length} + ${by[7].length} + ${by[9].length} prefixes, ${(out.length / 1024).toFixed(0)} KB`);
